algorithm: softmatch
save_dir: ./saved_models/usb_cv/
save_name: softmatch_sugarcane_40_0
resume: False
load_path: ./saved_models/usb_cv//softmatch_sugarcane_40_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 35
num_train_iter: 7000
num_log_iter: 250
num_eval_iter: 500
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 700
num_labels: 400
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
dist_align: True
dist_uniform: True
per_class: False
ema_p: 0.999
ulb_loss_ratio: 1.0
n_sigma: 2
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 5e-04
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: False
net: resnet50
net_from_name: True
data_dir: ./data
dataset: sugarcane
train_sampler: RandomSampler
num_classes: 5
num_workers: 2
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10012
dist_backend: nccl
gpu: 3
use_pretrain: False