algorithm: softmatch
save_dir: ./saved_models/usb_cv/
save_name: softmatch_sugarcane_40_0
resume: True
load_path: ./saved_models/usb_cv//softmatch_sugarcane_40_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 200
num_train_iter: 102400
num_log_iter: 256
num_eval_iter: 1024
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 40
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
dist_align: True
dist_uniform: True
per_class: False
ema_p: 0.999
ulb_loss_ratio: 1.0
n_sigma: 2
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 5e-05
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: resnet18
net_from_name: True
data_dir: ./data
dataset: sugarcane
train_sampler: RandomSampler
num_classes: 4
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10012
dist_backend: nccl
gpu: None
use_pretrain: False
pretrain_path: ""

