algorithm: freematch
save_dir: ./saved_models/usb_cv/
save_name: freematch_sugarcane_40_0
resume: False
load_path: ./saved_models/usb_cv//freematch_sugarcane_40_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 35
num_train_iter: 7000
num_log_iter: 250
num_eval_iter: 500
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 700
num_labels: 200
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
ema_p: 0.999
ent_loss_ratio: 0.001
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 5e-04
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: False
net: resnet18
net_from_name: True
data_dir: ./data
dataset: sugarcane
train_sampler: RandomSampler
num_classes: 5
num_workers: 2
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10011
dist_backend: nccl
gpu: 2
use_pretrain: False